#!/bin/bash
help(){
	echo "Fancontrol:"
    echo "Usage: fctrl [option]"
    echo
    echo "requires nbfc installed and configured."
	echo "Check https://aur.archlinux.org/packages/nbfc/ or https://github.com/hirschmann/nbfc"
	echo "note to self: use Acer Predator G3-572 profile"
    echo
    echo "  -f             full throttle"
    echo "  -a             auto"
    echo "  -h             displays this menu"
    echo 
    echo "Buy me a coffee realaravinth@batsense.net :)"
}

if [ -z $1 ]
then
	help
elif [ $1 == '-f' ]
then
	nbfc set -f 1 -s 100
	nbfc set -f 0 -s 100
elif [ $1 == '-a' ]
then
	nbfc set -f 1 -a
	nbfc set -f 0 -a
elif [ $1 == '-h' ]
then
	help
else
	echo "Error: $1 is not an option"
	help
fi
