#!/bin/bash

readonly SOCKFILE=/tmp/daily-events-asdfasdfasdf234234

create_file() {
	touch $SOCKFILE
}

show_cal() {
	readonly DAY=$(expr 12 \* 60 \* 60) 
	NOW=$(date +%s)
	FILE_DATE=$(stat --format=%Z $SOCKFILE)
	DIFF=$(expr $NOW - $FILE_DATE)

	echo $(expr $DIFF \> $DAY)
	return $(expr $DIFF \> $DAY)
}

if [ ! -e $SOCKFILE ]
then
	dnote v Calendar
	create_file
elif [ $(show_cal) -eq 1 ]
then
	dnote v Calendar
	rm $SOCKFILE
	touch $SOCKFILE
fi
