#!/bin/bash

CONFIG="./.config/monitor"

help(){
    echo "Usage: monitor [option]"
    echo
    echo "Works only on HDMI interfaces, in case the script doesn't work, run xrandr to see available interfaces "
    echo
    echo "  extends             left    extends monitor to the left"
    echo "                      right   extends monitor to the right"
    echo "  mirror                      mirrors monitor"
		echo " 	b										<0-1>		changes brightness"
		echo "	t										<2000-6000> changes temperature"
	echo "monitor		focus			toggles laptop display on and off"
    echo "  help                        displays this menu"
    echo 
    echo "Buy me a coffee realaravinth@batsense.net :)"
}



if [ ! -d $CONFIG ]
then
		mkdir -p $CONFIG
fi

if [ -z $1 ]
then
    help    
else
    if [ $1 == 'mirror' ]
    then
        xrandr --output HDMI-0 --mode 1920x1080 --same-as eDP-1-1
    elif [ $1 == 'extends' ]
        then
            if [ -z $2 ]
            then
                help
            else
                if [ $2 == right ]
                then
                    xrandr --output HDMI-0 --auto --right-of eDP-1-1
                elif [ $2 == 'left' ]
                then
                    xrandr --output HDMI-0 --auto --left-of eDP-1-1
                else
                    echo "Error: $2 is not an option"
                    help 
                fi
            fi
		elif [ $1 == 'b' ]
		then
				if [ -z $2 ]
				then
						help
				else
						xrandr --output eDP-1-1 --brightness $2
						xrandr --output HDMI-0  --brightness $2
						redshift -m randr -O $(cat $CONFIG/brightness)
				fi
		elif [ $1 == 't' ]
		then
				if [ -z $2 ]
				then
						help
				else
					echo $2 > $CONFIG/brightness
					redshift -m randr -O $2
				fi
	elif [ $1 == 'focus' ]
	then
			if [ -z $2 ]
			then help
			else
				if [ $2 == "off" ]
				then
					xrandr --output eDP-1-1 --off
				elif [ $2 == "on" ]
				then
					xrandr --output eDP-1-1 --auto
					monitor extends right
				else
					help
				fi
			fi
    else
        echo "Error: $1 is not an option"
        help 
    fi
fi
